import type { FeatureGroup } from './types';

export const REPO_URL =
  'https://github.com/sabuhiteymurov/expo-base/archive/refs/heads/main.tar.gz';

export const ALWAYS_EXCLUDE = [
  'cli/',
  '.github/',
  '.git/',
  'docs/',
  'CODE_OF_CONDUCT.md',
  'LICENSE',
  'README.md',
  'node_modules/',
  'ios/',
  'android/',
  'yarn.lock',
  'package-lock.json',
  'pnpm-lock.yaml',
  'bun.lockb',
];

export const FEATURE_GROUPS: FeatureGroup[] = [
  {
    id: 'state-management',
    label: 'State Management',
    description: 'Redux Toolkit + MMKV + Persist',
    deps: [
      '@reduxjs/toolkit',
      'react-redux',
      'redux-persist',
      'react-native-mmkv',
      'react-native-nitro-modules',
    ],
    devDeps: ['@types/react-redux'],
    files: ['src/store/'],
    scripts: [],
    plugins: [],
  },
  {
    id: 'i18n',
    label: 'Internationalization',
    description: 'i18next + expo-localization',
    deps: ['i18next', 'react-i18next', 'expo-localization'],
    devDeps: [],
    files: ['src/translations/', 'src/@types/'],
    scripts: [],
    plugins: ['expo-localization'],
  },
  {
    id: 'e2e-testing',
    label: 'E2E Testing',
    description: 'Detox',
    deps: [],
    devDeps: [
      'detox',
      'detox-expo-helpers',
      '@config-plugins/detox',
      'eslint-plugin-detox',
    ],
    files: ['e2e/', 'detox.config.js'],
    scripts: [
      'e2e:ios:build',
      'e2e:ios:test',
      'e2e:ios:debug:build',
      'e2e:ios:debug:test',
      'e2e:android:build',
      'e2e:android:test',
      'e2e:android:debug:build',
      'e2e:android:debug:test',
    ],
    plugins: ['@config-plugins/detox'],
  },
  {
    id: 'http-client',
    label: 'HTTP Client',
    description: 'Axios',
    deps: ['axios'],
    devDeps: [],
    files: ['src/services/'],
    scripts: [],
    plugins: [],
  },
  {
    id: 'forms',
    label: 'Forms & Validation',
    description: 'react-hook-form + zod',
    deps: ['react-hook-form', 'zod'],
    devDeps: [],
    files: [],
    scripts: [],
    plugins: [],
  },
  {
    id: 'ui-kit',
    label: 'UI Kit',
    description: 'Bottom Sheet, Flash List, Bottom Tabs, SVG, Size Matters',
    deps: [
      '@gorhom/bottom-sheet',
      '@shopify/flash-list',
      'react-native-bottom-tabs',
      'react-native-svg',
      'react-native-size-matters',
    ],
    devDeps: ['patch-package', 'postinstall-postinstall'],
    files: ['patches/', 'src/assets/svg/'],
    scripts: ['postinstall'],
    plugins: ['react-native-bottom-tabs'],
  },
  {
    id: 'animations',
    label: 'Animations',
    description: 'Reanimated + Worklets',
    deps: ['react-native-reanimated', 'react-native-worklets'],
    devDeps: [],
    files: [],
    scripts: [],
    plugins: [],
  },
  {
    id: 'network-info',
    label: 'Network Info',
    description: 'NetInfo + UUID',
    deps: ['@react-native-community/netinfo', 'react-native-uuid'],
    devDeps: [],
    files: [],
    scripts: [],
    plugins: [],
  },
];
